Fixing search url for django 1.10 and above.
For django 1.10 and above the search url will fail with a TypeError since there is no support for views as string insider urlpatterns, It will raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().